name: Scan MY Cloned Repo → Container Security

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker from MY repo
      run: docker build -t demo-app .

    - name: Trivy scans MY image (SARIF)
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'demo-app'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Download Custom Trivy HTML Template
      run: |
        mkdir -p contrib
        cat << 'EOF' > contrib/custom-html.tpl
        <html>
        <head>
        <title>Trivy Security Report</title>
        </head>
        <body>
        <h1>Container Vulnerability Report</h1>

        {{ range . }}
        <h2>Target: {{ .Target }}</h2>

        <table border="1" cellpadding="5">
        <tr>
        <th>Package</th>
        <th>Severity</th>
        <th>Installed Version</th>
        <th>Fixed Version</th>
        <th>Location / Layer</th>
        <th>Description</th>
        </tr>

        {{ range .Vulnerabilities }}
        <tr>
        <td>{{ .PkgName }}</td>
        <td>{{ .Severity }}</td>
        <td>{{ .InstalledVersion }}</td>
        <td>{{ .FixedVersion }}</td>
        <td>{{ .PkgPath }}</td>
        <td>{{ .Title }}</td>
        </tr>
        {{ end }}

        </table>
        {{ end }}

        </body>
        </html>
        EOF

    - name: Trivy Scan HTML Report
      run: |
        trivy image \
        --format template \
        --template "@contrib/custom-html.tpl" \
        -o trivy-report.html demo-app

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-html-report
        path: trivy-report.html

    - name: Upload to Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
