name: Scan MY Cloned Repo → Container Security

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker from MY repo
      run: docker build -t demo-app .

    - name: Trivy scans MY image
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'demo-app'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Download Trivy HTML Template
      run: |
        mkdir -p contrib
        curl -L https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o contrib/html.tpl

    - name: Modify Template to Show Location
      run: |
        sed -i 's/<th>Fixed Version<\/th>/<th>Fixed Version<\/th><th>Location<\/th>/' contrib/html.tpl
        sed -i 's/<td>{{ .FixedVersion }}<\/td>/<td>{{ .FixedVersion }}<\/td><td>{{ .PkgPath }}<\/td>/' contrib/html.tpl

    - name: Generate Trivy HTML Report
      run: |
        trivy image \
        --format template \
        --template "@contrib/html.tpl" \
        -o trivy-report.html demo-app

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-html-report
        path: trivy-report.html

    - name: Upload to Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
